### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by tajnymag** [SimonTamas/TiledChunks#3]
Hi, I've found the thread you started on HTML5Developers. Ive been also noticing the huge lag when camera moves. Could you please provide a simple guide on how to use it? Also, does it work with phaser 2.4.6?

**Comment by bliser47** [comment]
Hi, sorry for the very late response. Yes it works with 2.4.6. I will try to make a full documentation after I have finished the game I am using this for.

**Comment by SimonTamas** [comment]
I wrote a little starting guide, will update it as questions come in.
